### ISSUE TITLE
Next 6 month road map as software engineer?

### ISSUE THREAD

**Issue by vgrch** [goupaz/0-to-hero#10]
I am a backend developer that approximately 3 years of hands-on experience as a java developer.
After failure recent interview processes I decided to improve my skills on these branches. 
I am open any suggestion to make reform my road map. Thank in advance.

*Algorithms
Learn implementation of most known algorithms(Sorting, searching, etc.).
Practice hackerrank, leetcode, dailycodingproblem.
Practice whiteboard coding.
*DataStructures
Learn all available DS in CS.
Learn how to implement your own data structure.
*Java
Improve core java skills including multithreading, serializable, socket programming and etc.
Improve framework skills (Spring boot).
Design patterns.
Unit testing.
*Operations
Linux from Evi Nemeth.
Learn about DevOps tools and technologies.
Learn network fundamentals. (OSI layers, network protocols, subnetting, etc.)
Architectural design.

**Comment by Arlington1985** [comment]
Your roadmap is pretty solid and also tough I would say. You are a hero if you can do it. Also maybe include some FrontEnd stuff optionally?

**Comment by vgrch** [comment]
There are some front end technologies like angular, react in my backlog. I decided to learn the mentioned technologies when I feel comfortable at the backend. for my prediction, this will happen in the first quarter of 2020.

**Comment by sakomws** [comment]
@vgrch I dont think its right one, let me do one for u this evening.

**Comment by vgrch** [comment]
I made the schedule:
Mondays and Thursday: Algorithms and DS.
Tuesday and Friday: Core Java and framework
Wednesday: Operations
I can dedicate about 2 hours every day. 

It would be better to hear any recommendation from you.

**Comment by sakomws** [comment]
So, will go to more details, for now you can start:

1. Language: Python3
2. Algorithm https://github.com/goupaz/0-to-hero/blob/master/algorithms_plan.md
3. Leetcode: Easy ones only
4. Data Structures (coming)
5. OS: Ubuntu (coming)
6. 1 Open source contribution: written in Python3, preferable Django Framework

**Comment by vgrch** [comment]
Update the current state. Currently preparing Java8 OCA exam. 
Watching algorithms & data structure [course](https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms)
Reading [this](https://www.amazon.com/Clean-Coder-Conduct-Professional-Programmers/dp/0137081073) book




- *Algorithms
- [X] - Learn implementation of most known algorithms(Sorting, searching, etc.).
- [X] - Practice hackerrank, leetcode, dailycodingproblem.
- [ ] - Practice whiteboard coding.
-  *DataStructures
- [X] - Learn all available DS in CS.
- [ ] - Learn how to implement your own data structure.
- *Java
- [X] - Improve core java skills including multithreading, serializable, socket programming and etc.
- [X] - Improve framework skills (Spring boot).
- [ ] - Design patterns.
- [ ] - Unit testing.
-  *Operations
- [ ] - Linux from Evi Nemeth.
- [X] - Learn about DevOps tools and technologies.
- [ ] - Learn network fundamentals. (OSI layers, network protocols, subnetting, etc.)
- [ ] - Architectural design.

**Comment by sakomws** [comment]
Good job @vgrch please, keep sharing your experiences. We are here to support you!
